export const CARGOS_VETERINARIOS = [
  { value: 'Médico Veterinário', label: 'Médico Veterinário' },
  { value: 'Auxiliar de Veterinária', label: 'Auxiliar de Veterinária' },
  { value: 'Técnico em Veterinária', label: 'Técnico em Veterinária' },
  { value: 'Zootecnista', label: 'Zootecnista' },
  { value: 'Estagiário de Veterinária', label: 'Estagiário de Veterinária' },
  { value: 'Tosador', label: 'Tosador' },
  { value: 'Banhista', label: 'Banhista' },
  { value: 'Auxiliar de Pet Shop / Estética Animal', label: 'Auxiliar de Pet Shop / Estética Animal' },
  { value: 'Recepcionista', label: 'Recepcionista' },
  { value: 'Atendente', label: 'Atendente' },
  { value: 'Gerente', label: 'Gerente' },
  { value: 'Administrador', label: 'Administrador' },
  { value: 'Auxiliar de Serviços Gerais / Limpeza', label: 'Auxiliar de Serviços Gerais / Limpeza' },
  { value: 'Contador', label: 'Contador' },
  { value: 'Profissional de Marketing / Social Media', label: 'Profissional de Marketing / Social Media' },
  { value: 'Técnico em Análises Clínicas', label: 'Técnico em Análises Clínicas' },
  { value: 'Outros', label: 'Outros' },
];

export const ESPECIES_ANIMAIS = [
  { value: 'Cachorro', label: 'Cachorro' },
  { value: 'Gato', label: 'Gato' },
  { value: 'Coelho', label: 'Coelho' },
  { value: 'Hamster', label: 'Hamster' },
  { value: 'Porquinho-da-índia', label: 'Porquinho-da-índia (cobaia)' },
  { value: 'Furão', label: 'Furão' },
  { value: 'Chinchila', label: 'Chinchila' },
  { value: 'Gerbil', label: 'Gerbil' },
  { value: 'Mini porco', label: 'Mini porco (porco doméstico)' },
  { value: 'Periquito-australiano', label: 'Periquito-australiano' },
  { value: 'Calopsita', label: 'Calopsita' },
  { value: 'Canário', label: 'Canário' },
  { value: 'Papagaio', label: 'Papagaio' },
  { value: 'Agapornis', label: 'Agapornis (inseparável)' },
  { value: 'Cacatua', label: 'Cacatua' },
  { value: 'Betta', label: 'Betta' },
  { value: 'Goldfish', label: 'Goldfish (peixe dourado)' },
  { value: 'Guppy', label: 'Guppy' },
  { value: 'Molinésia', label: 'Molinésia' },
  { value: 'Neon Tetra', label: 'Neon Tetra' },
  { value: 'Tartaruga', label: 'Tartaruga' },
  { value: 'Jabuti', label: 'Jabuti' },
  { value: 'Iguana', label: 'Iguana' },
  { value: 'Cágado', label: 'Cágado' },
  { value: 'Lagarto-leopardo', label: 'Lagarto-leopardo (gecko)' },
  { value: 'Outros', label: 'Outros' },
];

export const VACINAS = [
  { value: 'V8', label: 'V8' },
  { value: 'V10', label: 'V10' },
  { value: 'Antirrábica', label: 'Antirrábica' },
  { value: 'Giárdia', label: 'Giárdia' },
  { value: 'Tosse dos Canis', label: 'Tosse dos Canis (traqueobronquite infecciosa)' },
  { value: 'Leptospirose', label: 'Leptospirose' },
  { value: 'Coronavirose', label: 'Coronavirose' },
  { value: 'Parvovirose Cães', label: 'Parvovirose (reforço individual em filhotes)' },
  { value: 'V3', label: 'V3' },
  { value: 'V4', label: 'V4' },
  { value: 'V5', label: 'V5' },
  { value: 'FELV', label: 'FELV (Leucemia Felina)' },
  { value: 'Clamidiose Felina', label: 'Clamidiose Felina' },
  { value: 'Panleucopenia Felina', label: 'Panleucopenia Felina' },
  { value: 'Rinotraqueíte', label: 'Rinotraqueíte' },
  { value: 'Calicivirose', label: 'Calicivirose' },
  { value: 'Mixomatose', label: 'Mixomatose' },
  { value: 'Doença Hemorrágica Viral', label: 'Doença Hemorrágica Viral (DHV)' },
  { value: 'Pasteurelose', label: 'Pasteurelose' },
  { value: 'Influenza Equina', label: 'Influenza Equina' },
  { value: 'Tétano', label: 'Tétano' },
  { value: 'Encefalomielite Equina', label: 'Encefalomielite Equina' },
  { value: 'Raiva', label: 'Raiva' },
  { value: 'Adenite Equina', label: 'Adenite Equina (Garrotilho)' },
  { value: 'Febre Aftosa', label: 'Febre Aftosa' },
  { value: 'Brucelose', label: 'Brucelose' },
  { value: 'Carbúnculo Sintomático', label: 'Carbúnculo Sintomático' },
  { value: 'Botulismo', label: 'Botulismo' },
  { value: 'Enterotoxemia', label: 'Enterotoxemia' },
  { value: 'IBR/IPV', label: 'IBR/IPV (Rinotraqueíte e Vulvovaginite Infecciosa)' },
  { value: 'Diarreia Viral Bovina', label: 'Diarreia Viral Bovina (BVD)' },
  { value: 'Peste Suína Clássica', label: 'Peste Suína Clássica' },
  { value: 'Parvovirose Suínos', label: 'Parvovirose (Suínos)' },
  { value: 'Erysipelose', label: 'Erysipelose (Mal Rubro)' },
  { value: 'Colibacilose', label: 'Colibacilose' },
  { value: 'Clostridiose', label: 'Clostridiose' },
  { value: 'Circovirose Suína', label: 'Circovirose Suína' },
  { value: 'Clostridioses', label: 'Clostridioses (Carbúnculo, Enterotoxemia, Tétano etc.)' },
  { value: 'Ectima Contagioso', label: 'Ectima Contagioso' },
  { value: 'Linfadenite Caseosa', label: 'Linfadenite Caseosa' },
  { value: 'NewCastle', label: 'NewCastle (Pseudopeste)' },
  { value: 'Bouba Aviária', label: 'Bouba Aviária' },
  { value: 'Gumboro', label: 'Gumboro (Doença Infecciosa da Bursa)' },
  { value: 'Bronquite Infecciosa', label: 'Bronquite Infecciosa' },
  { value: 'Encefalomielite Aviária', label: 'Encefalomielite Aviária' },
  { value: 'Coriza Infecciosa', label: 'Coriza Infecciosa' },
  { value: 'Varíola Aviária', label: 'Varíola Aviária' },
  { value: 'Streptococose', label: 'Streptococose' },
  { value: 'Lactococose', label: 'Lactococose' },
  { value: 'Francisellose', label: 'Francisellose' },
  { value: 'Outros', label: 'Outros' },
];

export const FABRICANTES_VACINAS = [
  { value: 'Antigen', label: 'Antigen Tecnologia de Vacinas Aplicada à Saúde Animal' },
  { value: 'Biogénesis Bagó', label: 'Biogénesis Bagó' },
  { value: 'Syntec', label: 'Syntec (laboratório veterinário brasileiro)' },
  { value: 'Tecpar', label: 'Tecpar (Instituto de Tecnologia do Paraná)' },
  { value: 'Zoetis', label: 'Zoetis' },
  { value: 'Boehringer Ingelheim', label: 'Boehringer Ingelheim Animal Health' },
  { value: 'Ceva', label: 'Ceva Santé Animale' },
  { value: 'Merck Animal Health', label: 'Merck Animal Health' },
  { value: 'Virbac', label: 'Virbac' },
  { value: 'Hester Biosciences', label: 'Hester Biosciences (Índia)' },
  { value: 'HIPRA', label: 'HIPRA (Espanha)' },
  { value: 'Phibro Animal Health', label: 'Phibro Animal Health Corporation' },
  { value: 'AdvaCare Pharma', label: 'AdvaCare Pharma' },
  { value: 'Outros', label: 'Outros' },
];

